apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sasya-chikitsa-argo-apps-all
  namespace: openshift-gitops
spec:
  destination:
    namespace: sasya-chikitsa
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: platform-engineering/base/argo-apps/
    repoURL: 'https://github.com/cds-9-group-6/sasya-chikitsa.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin-binding
  namespace: sasya-chikitsa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops