apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlruns
  namespace: sasya-chikitsa
  labels:
    app: mlflow-server
    app.kubernetes.io/component: mlflow-server
    app.kubernetes.io/instance: mlflow-server
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/part-of: mlflow-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Adjust based on your MLflow data requirements
  storageClassName: gp3-csi  # Use appropriate storage class for your OpenShift cluster