apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: otel-collector-base

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: kustomize

images:
  - name: otel/opentelemetry-collector-contrib
    newTag: latest
