apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-data-pvc
  namespace: your-namespace  # Replace with your actual namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size based on your data requirements
  storageClassName: gp2  # Use appropriate storage class for your OpenShift cluster
