apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
    app.kubernetes.io/component: engine
    app.kubernetes.io/instance: engine
    app.kubernetes.io/name: engine
    app.kubernetes.io/part-of: sasya-arogya
    app.openshift.io/runtime: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
        app.kubernetes.io/component: engine
        app.kubernetes.io/name: engine
        deployment: engine
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: engine
          image: quay.io/rajivranjan/engine:amd64-v5
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: OLLAMA_HOST
              value: http://ollama.sasya-arogya.svc.cluster.local:11434
            - name: HUB_MODEL_ID
              value: sentence-transformers/multi-qa-MiniLM-L6-cos-v1
            - name: OLLAMA_MODEL
              value: llama3.1:8b
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
