apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    app.kubernetes.io/component: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: sasya-arogya
    app.openshift.io/runtime: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
        deployment: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
              name: http
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              readOnly: true
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-dashboard-aiops
              mountPath: /etc/grafana/provisioning/dashboards/aiops
              readOnly: true
            - name: grafana-dashboard-datascientists
              mountPath: /etc/grafana/provisioning/dashboards/datascientists
              readOnly: true
            - name: grafana-dashboard-executive
              mountPath: /etc/grafana/provisioning/dashboards/executive
              readOnly: true
            - name: grafana-dashboard-engine-overview
              mountPath: /etc/grafana/provisioning/dashboards/engine-overview
              readOnly: true
            - name: grafana-dashboard-intent-analytics
              mountPath: /etc/grafana/provisioning/dashboards/intent-analytics
              readOnly: true
            - name: grafana-dashboard-langgraph-metrics
              mountPath: /etc/grafana/provisioning/dashboards/langgraph-metrics
              readOnly: true
            - name: grafana-dashboard-ml-performance
              mountPath: /etc/grafana/provisioning/dashboards/ml-performance
              readOnly: true
      env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_INSTALL_PLUGINS
          value: ""
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
            items:
              - key: grafana.ini
                path: grafana.ini
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards-config
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage
        - name: grafana-dashboard-aiops
          configMap:
            name: grafana-dashboard-aiops
        - name: grafana-dashboard-datascientists
          configMap:
            name: grafana-dashboard-datascientists
        - name: grafana-dashboard-executive
          configMap:
            name: grafana-dashboard-executive
        - name: grafana-dashboard-engine-overview
          configMap:
            name: grafana-dashboard-engine-overview
        - name: grafana-dashboard-intent-analytics
          configMap:
            name: grafana-dashboard-intent-analytics
        - name: grafana-dashboard-langgraph-metrics
          configMap:
            name: grafana-dashboard-langgraph-metrics
        - name: grafana-dashboard-ml-performance
          configMap:
            name: grafana-dashboard-ml-performance
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
