apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: chromadb
        resources: {}
          # requests:
          #   memory: "500Mi"
          #   cpu: "100m"
          # limits:
          #   memory: "1Gi"
          #   cpu: "500m"
