apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: engine
        resources: {}
          # requests:
          #   memory: "1Gi"
          #   cpu: "250m"
          # limits:
          #   memory: "2Gi"
          #   cpu: "1"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
