apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: engine
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
        env:
        - name: LOG_LEVEL
          value: "INFO"
