apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: mlflow-server
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 4
            memory: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlruns
spec:
  resources:
    requests:
      storage: 10Gi  # Larger storage for prod
