apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: prescription
        resources:
          requests:
            memory: "3Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "3"
        env:
        - name: LOG_LEVEL
          value: "INFO"
