apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: prescription
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: LOG_LEVEL
          value: "INFO"
