apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
    app.kubernetes.io/component: mlflow-server
    app.kubernetes.io/instance: mlflow-server
    app.kubernetes.io/name: mlflow-server
    app.kubernetes.io/part-of: sasya-arogya
    app.openshift.io/runtime: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
        app.kubernetes.io/component: mlflow-server
        app.kubernetes.io/name: mlflow-server
        deployment: mlflow-server
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: mlflow-server
          image: quay.io/rajivranjan/mlflow-server:amd64-v1
          securityContext:
            runAsUser: 0
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
              protocol: TCP
              name: http
          envFrom:
            - configMapRef:
                name: mlflow-config
          volumeMounts:
            - name: mlruns
              mountPath: /mlruns
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2
              memory: 4Gi
      volumes:
        - name: mlruns
          persistentVolumeClaim:
            claimName: mlruns
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600
