apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mlflow-tracking-base

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - configmap.yaml
  - pvc.yaml

commonLabels:
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: kustomize

images:
  - name: quay.io/rajivranjan/mlflow-server
    newTag: amd64-v1
