apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sasya-arogya-argo-apps-llama318b
  namespace: openshift-gitops
spec:
  destination:
    namespace: sasya-arogya
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: base/ollama-both/
    repoURL: 'https://github.com/cds-9-group-6/platform-engineering.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
