apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ollama
        resources: {}
          # requests:
          #   cpu: '500m'
          #   memory: 1Gi
          # limits:
          #   cpu: '2'
          #   memory: 4Gi
