apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: prescription
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
