apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: prescription
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
